### ISSUE TITLE
Not single page enough

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/scoreboard#11]
# needsmoreangular
# truefacts

---
- [x] Home
  - [x] homepage
  - [x] login
  - [x] logout
- [x] Member
  - [x] Show
- [x] Membership
  - [x] index
  - [x] new
- [x] Committee
  - [x] new
- [x] Semester
  - [x] new
  - [x] show

**Comment by 7imbrook** [comment]
`#needsHipperCode`
