### ISSUE TITLE
New scoreboard API endpoints always have a content-type header of text/html

### ISSUE THREAD

**Issue by weswigham** [rit-sse/scoreboard#16]
It's probably a problem, considering it should be application/json?

**Comment by kristenmills** [comment]
Well it's working so I don't know what the issue is.

**Comment by kristenmills** [comment]
Also I just checked and I don't believe that's true. So unless you can prove to me otherwise, I'm closing this issue.

**Edit:**
`/api/member/:dcd`
`/api/semester/:name`
had the wrong content-type header
They rest were fine. 
I'm fixing it. Wait for it. It will happen.

**Comment by weswigham** [comment]
![headers](https://cloud.githubusercontent.com/assets/2932786/4176094/db939a3c-35f3-11e4-9cce-940db36b7314.png)

Says text/html

**Comment by kristenmills** [comment]
Read my edits

**Comment by weswigham** [comment]
you mean commit message? :+1:

**Comment by kristenmills** [comment]
No. 

See the comment right before yours

**Comment by kristenmills** [comment]
Only 2 of the endpoints had the wrong content-type. Not all of them.

**Comment by weswigham** [comment]
Ahh, okay.
