### ISSUE TITLE
Can only see the 15 memberships

### ISSUE THREAD

**Issue by evajurman** [rit-sse/scoreboard#19]
It is unclear that there are more than 15 memberships (https://sse.rit.edu/scoreboard/memberships).

There either needs to be a button to expand or it needs to be in text that there is more, and these are the 15 most recent.

**Comment by nickserv** [comment]
As a temporary fix, does the system display past these 15 memberships anywhere?

**Comment by bbesmanoff** [comment]
The API paginates at 15, which is probably the culprit

**Comment by weswigham** [comment]
I remember there used to be a `show more` link at the bottom of the page. Did it fall away during the redesign?

**Comment by bbesmanoff** [comment]
In other news, this should be in [scoreboard-2.0](https://github.com/rit-sse/scoreboard-2.0)
