### ISSUE TITLE
As a member on coop, I want to appear on the scoreboard

### ISSUE THREAD

**Issue by weswigham** [rit-sse/scoreboard#3]
Title.

**Comment by kristenmills** [comment]
You will. I have only done officer memberships so far.

**Comment by weswigham** [comment]
Are we adding coops by hand each semester?

**Comment by kristenmills** [comment]
The only real way to add memberships is by hand.

**Comment by weswigham** [comment]
No way to just mark a previous member as on coop for a semester then, I suppose. Ah well.

**Comment by kristenmills** [comment]
https://sse.se.rit.edu/scoreboard/members/waw5336

**Comment by weswigham** [comment]
But I'm not on the scoreboard itself? Yet?

**Comment by kristenmills** [comment]
Well it only shows the top 10. I've already added 13. You need to earn more memberships...on co-op

**Comment by kristenmills** [comment]
I should make it show everybody

**Comment by kristenmills** [comment]
that makes sense

**Comment by weswigham** [comment]
Add an 'expand' button so it can be used like a membership list.

**Comment by weswigham** [comment]
Or just make it show everybody.

**Comment by weswigham** [comment]
that makes sense.

**Comment by kristenmills** [comment]
https://sse.se.rit.edu/scoreboard

**Comment by kristenmills** [comment]
You are there now

**Comment by weswigham** [comment]
We are the greatest at rapid website updates now. So nice.

**Comment by kristenmills** [comment]
The BEST
